PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE USER(
	USERNAME 	VARCHAR(30) PRIMARY KEY NOT NULL,
	PASSWORD 	VARCHAR(30) NOT NULL,
	EMAIL 		TEXT NOT NULL,
	FIRST_NAME	VARCHAR(30) NOT NULL,
	LAST_NAME 	VARCHAR(70) NOT NULL,
	BDAY		INTEGER NOT NULL,
	BMONTH		TEXT NOT NULL,
	BYEAR		INTEGER NOT NULL,
	IMG_NAME	TEXT NOT NULL
);
INSERT INTO USER VALUES('francisMaria','PasswordAs173','fran@hotmail.com','Francisco','Maria',16,'september',1998,'francisMaria.jpg');
COMMIT;
